server:
  port: ${BASE_PORT}

spring:
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      authentication-database: ${MONGODB_AUTH}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      database: ${MONGODB_DBNAME}

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  security:
    jwt:
      secret: ${JWT_KEY}
      refreshTokenSecret: ${REFRESH_KEY}
cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ${S3_BUCKET_REGION}
    stack:
      auto: false

sns:
  service:
    api-key: ${SNS_SERVICE_API_KEY}
    api-secret-key: ${SNS_SERVICE_API_SECRET_KEY}