server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://silvercareerdb.coceqfygqpmk.ap-northeast-2.rds.amazonaws.com:3306/silcarDB?autoReconnect=true
    username: silvermaster
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      host: 43.201.132.241
      port: 27017
      authentication-database: admin
      username: admin1
      password: test1234
      database: silcarMongoDB



kakao-open-api:
  auth:
    rest-api-key: 3fc7941e2346eb6d089f1032ffe4c40b

sns:
  service:
    api-key: ${SNS_SERVICE_API_KEY}
    api-secret-key: ${SNS_SERVICE_API_SECRET_KEY}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace